import { env } from "../env.js";
import type { InterviewType } from "../types.js";
import { PERSONAS } from "./persona.js";

// Vapi's built-in voices (provider "vapi") — no third-party voice key required.
// Swap these voiceIds for ElevenLabs/PlayHT/etc. if you prefer.
const VOICE_BY_TYPE: Record<InterviewType, string> = {
  behavioral: "Paige",
  technical: "Cole",
  system_design: "Neha",
  hr: "Elliot",
};

// Build the transient Vapi assistant the browser hands to vapi.start().
// The key part is model.provider = "custom-llm" pointing at OUR webhook: Vapi
// handles mic/STT/TTS/turn-taking, but every reply is generated by our engine.
export function buildVapiAssistant(params: {
  interviewToken: string;
  opening: string;
  type: InterviewType;
}) {
  const { interviewToken, opening, type } = params;
  const persona = PERSONAS[type];

  return {
    name: `Mentorque ${persona.label} Interviewer`,
    firstMessage: opening,
    // Vapi appends "/chat/completions" to this base URL.
    model: {
      provider: "custom-llm",
      url: `${env.PUBLIC_SERVER_URL}/api/interview/webhook/${interviewToken}`,
      model: "mentorque-interviewer",
      // Our server sends the full context each turn; no need for Vapi to stream
      // partial user input to the LLM.
    },
    transcriber: {
      provider: "deepgram",
      model: "nova-2",
      language: "en",
    },
    voice: {
      provider: "vapi",
      voiceId: VOICE_BY_TYPE[type],
    },
    // Keep interviews bounded (cost + focus). ~18 minutes hard cap.
    maxDurationSeconds: 1080,
    silenceTimeoutSeconds: 30,
    backgroundDenoisingEnabled: true,
    metadata: { interviewType: type },
  };
}
